### ISSUE TITLE
what to enter

### ISSUE THREAD

**Issue by sid8840** [iammukeshm/cowin-vaccine-notifier#1]
after the trigger created in IFTTT,
what values must be entered to get it run??

**Comment by iammukeshm** [comment]
I hope this should help. Let me know if any other queries.
https://user-images.githubusercontent.com/31455818/116820335-1e7cc380-ab92-11eb-9d8d-a5ef5a29f2ba.mp4

**Comment by sid8840** [comment]
sir, then how to use this webhook api key of the individual for this purpose?

**Comment by iammukeshm** [comment]
I assume that you have already received your API key. Simply paste your API key in the appsettings.json in the corresponding field.

**Comment by sid8840** [comment]
sir can you screen record the whole process and send it to sid8840@gmail.com??
that would be huge help sir.

**Comment by iammukeshm** [comment]
Please use your own API Key.
https://user-images.githubusercontent.com/31455818/116821908-9c909880-ab99-11eb-820a-78712023b7f6.mp4

**Comment by sid8840** [comment]
the last part with visual studio was awesome.
you are great sir.
